export const PREDYX_MUSCLE_IDS = [
  'muscle_chest',
  'muscle_front_delt',
  'muscle_side_delt',
  'muscle_rear_delt',
  'muscle_biceps',
  'muscle_triceps',
  'muscle_lats',
  'muscle_traps_upper',
  'muscle_traps_mid',
  'muscle_forearms',
  'muscle_abs',
  'muscle_obliques',
  'muscle_erectors',
  'muscle_quads',
  'muscle_hamstrings',
  'muscle_glutes',
  'muscle_adductors',
  'muscle_hip_flexors',
  'muscle_calves',
] as const;

export type MuscleHighlightId = typeof PREDYX_MUSCLE_IDS[number];

export const MUSCLE_METADATA: Record<MuscleHighlightId, { name: string; region: 'Upper Body' | 'Core' | 'Lower Body'; cue: string }> = {
  muscle_chest: { name: 'Pectoralis Major & Minor', region: 'Upper Body', cue: 'Adduct humerus across midline with scapular retraction.' },
  muscle_front_delt: { name: 'Anterior Deltoid', region: 'Upper Body', cue: 'Drive upward in sagittal plane maintaining clavicular stability.' },
  muscle_side_delt: { name: 'Lateral Deltoid', region: 'Upper Body', cue: 'Abduct in the scapular plane with slight internal rotation.' },
  muscle_rear_delt: { name: 'Posterior Deltoid', region: 'Upper Body', cue: 'Horizontal abduction with neutral spinal alignment.' },
  muscle_biceps: { name: 'Biceps Brachii', region: 'Upper Body', cue: 'Supinate forearm during elbow flexion for peak contraction.' },
  muscle_triceps: { name: 'Triceps Brachii', region: 'Upper Body', cue: 'Full elbow extension locking lateral and long heads.' },
  muscle_lats: { name: 'Latissimus Dorsi', region: 'Upper Body', cue: 'Depress scapulae and drive elbows down toward pelvis.' },
  muscle_traps_upper: { name: 'Upper Trapezius', region: 'Upper Body', cue: 'Elevate clavicles with controlled eccentric descent.' },
  muscle_traps_mid: { name: 'Mid Trapezius & Rhomboids', region: 'Upper Body', cue: 'Retract scapulae forcefully against thoracic cage.' },
  muscle_forearms: { name: 'Brachioradialis & Forearm Flexors', region: 'Upper Body', cue: 'Maintain rigid neutral wrist alignment during loading.' },
  muscle_abs: { name: 'Rectus Abdominis', region: 'Core', cue: 'Posterior pelvic tilt with thoracic rib cage depression.' },
  muscle_obliques: { name: 'Internal & External Obliques', region: 'Core', cue: 'Anti-rotational intra-abdominal pressure bracing.' },
  muscle_erectors: { name: 'Erector Spinae', region: 'Core', cue: 'Isometric axial spinal extension resisting anterior shear.' },
  muscle_quads: { name: 'Quadriceps Femoris', region: 'Lower Body', cue: 'Extend knee through midfoot drive with vertical torso.' },
  muscle_hamstrings: { name: 'Hamstring Complex (Biceps Femoris)', region: 'Lower Body', cue: 'Hip hinge loading posterior chain with active tension.' },
  muscle_glutes: { name: 'Gluteus Maximus & Medius', region: 'Lower Body', cue: 'Extend hips forcefully with neutral pelvis at lockout.' },
  muscle_adductors: { name: 'Adductor Magnus & Longus', region: 'Lower Body', cue: 'Stabilize femur in frontal plane during deep squat depth.' },
  muscle_hip_flexors: { name: 'Iliopsoas Complex', region: 'Lower Body', cue: 'Control hip deceleration during eccentric extension.' },
  muscle_calves: { name: 'Gastrocnemius & Soleus', region: 'Lower Body', cue: 'Plantarflex through first metatarsal for peak tension.' },
};

export const MODEL_NODE_TO_PREDYX_ID: Record<string, MuscleHighlightId> = {
  mesh_muscle_chest_L: 'muscle_chest',
  mesh_muscle_chest_R: 'muscle_chest',
  mesh_muscle_front_delt_L: 'muscle_front_delt',
  mesh_muscle_front_delt_R: 'muscle_front_delt',
  mesh_muscle_side_delt_L: 'muscle_side_delt',
  mesh_muscle_side_delt_R: 'muscle_side_delt',
  mesh_muscle_rear_delt_L: 'muscle_rear_delt',
  mesh_muscle_rear_delt_R: 'muscle_rear_delt',
  mesh_muscle_traps_upper: 'muscle_traps_upper',
  mesh_muscle_traps_mid: 'muscle_traps_mid',
  mesh_muscle_lats_L: 'muscle_lats',
  mesh_muscle_lats_R: 'muscle_lats',
  mesh_muscle_erectors: 'muscle_erectors',
  mesh_muscle_abs: 'muscle_abs',
  mesh_muscle_obliques_L: 'muscle_obliques',
  mesh_muscle_obliques_R: 'muscle_obliques',
  mesh_muscle_biceps_L: 'muscle_biceps',
  mesh_muscle_biceps_R: 'muscle_biceps',
  mesh_muscle_triceps_L: 'muscle_triceps',
  mesh_muscle_triceps_R: 'muscle_triceps',
  mesh_muscle_forearms_L: 'muscle_forearms',
  mesh_muscle_forearms_R: 'muscle_forearms',
  mesh_muscle_glutes_L: 'muscle_glutes',
  mesh_muscle_glutes_R: 'muscle_glutes',
  mesh_muscle_hip_flexors_L: 'muscle_hip_flexors',
  mesh_muscle_hip_flexors_R: 'muscle_hip_flexors',
  mesh_muscle_quads_L: 'muscle_quads',
  mesh_muscle_quads_R: 'muscle_quads',
  mesh_muscle_hamstrings_L: 'muscle_hamstrings',
  mesh_muscle_hamstrings_R: 'muscle_hamstrings',
  mesh_muscle_adductors_L: 'muscle_adductors',
  mesh_muscle_adductors_R: 'muscle_adductors',
  mesh_muscle_calves_L: 'muscle_calves',
  mesh_muscle_calves_R: 'muscle_calves',
};
